fix(dracut-install): build with -Werror=discarded-qualifiers
```
src/install/dracut-install.c:475:11: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  475 |         q = strstr(lib, ".so.");
```

- `q` cannot be const, because it's also used for `q = strstr(clib, ".so.");`,
removing the suffix from clib via `q[3] = '\0';`, so create two variables to get
the suffix offsets, one const for `lib`, other non-const for `clib`.

```
src/install/dracut-install.c:2592:11: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
 2592 |         p = strstr(abskpath, "/lib/modules/");
```

- `p` can be const like `abskpath`, since it's not modified.

Fixes #1877