chore: version lock commisery-action
@master seems to report the folloeing error

Error: Resource not accessible by integration

Switch to @v3, as it is the last stable version.